name: ML Pipeline 

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build_runtime:
    name: Build Runtime Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Runtime Docker Image
        run: |
          # Перетворюємо репозиторій у lowercase для Docker
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          docker build --target runtime -t ghcr.io/$REPO_LOWER/speech-model:latest .

      - name: Push Docker Image to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_LOWER/speech-model:latest

  validate_model:
    name: Validate Model & Measure Latency
    runs-on: ubuntu-latest
    needs: build_runtime
    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install torch torchaudio numpy tqdm

      - name: Run Validation with Pretrained Model
        run: python validate_model.py








