name: ML Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ format('ghcr.io/{0}/{1}', github.repository_owner, 'speech-model') }}
  TRAIN_LOG: train.log
  METRICS_FILE: metrics.json

jobs:
  train:
    name: Train Model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Trainer Image
        run: |
          docker build --target trainer -t trainer-image .

      - name: Run Training Container (short test)
        run: |
          mkdir -p artifacts
          docker run --rm \
            -v ${{ github.workspace }}/artifacts:/artifacts \
            trainer-image \
            python train.py --save-model /artifacts/model.pth --epochs 1 --download-data

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: artifacts/model.pth

      - name: Upload training log
        uses: actions/upload-artifact@v4
        with:
          name: train-log
          path: ${{ env.TRAIN_LOG }}

  inference:
    name: Build Inference Image
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: artifacts/

      - name: Build Runtime Docker Image
        run: |
          docker build --target runtime -t $IMAGE_NAME .

      - name: Push Docker Image to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker push $IMAGE_NAME

      - name: Save runtime image as artifact
        run: |
          mkdir -p artifacts
          docker save $IMAGE_NAME -o artifacts/runtime-image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: runtime-image
          path: artifacts/runtime-image.tar

  validate_model:
    name: Validate Model & Measure Latency
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: artifacts/

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install torch torchaudio numpy

      - name: Run Validation with Real Test Audio
        run: python validate_model.py


